---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    username: "{{ ansible_ssh_user }}"

  tasks:
    - name: tap repositories
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - homebrew/binary
        - caskroom/cask
        - caskroom/fonts

    - name: install homebrew packages
      homebrew: name={{ item }} state=latest update_homebrew=no upgrade_all=no
      with_items:
        - cocoapods
        - fabric
        - gibo
        - hh
        - ideviceinstaller
        - ios-deploy
        - node
        - pwgen
        - swiftlint
        - the_silver_searcher
        - tig
        - tree
        - wget
        - yarn

    - name: install homebrew cask packages
      homebrew_cask: name={{ item }} state=present
      with_items:
        - alfred
        - android-studio
        - avira-antivirus
        - clipy
        - coteditor
        - docker
        - dropbox
        - firefox
        - ganttproject
        - evernote
        - google-chrome
        # permission problem..
        #- google-cloud-sdk
        - google-japanese-ime
        - iterm2
        - java
        - kindle
        - macvim
        - slack
        - skitch
        - skype
        - sourcetree
        - visual-studio-code
        - virtualbox
        # appstore LICENSE problem
        #- moom
        # not exists in cask
        #- carthage
        #- feedly
        #- todoist
        #- wunderlist
        #- google file stream
        #- Synology Note Station

    - name: install Bash-it
      git:
        repo: https://github.com/Bash-it/bash-it.git
        dest: /Users/{{ username }}/.bash_it
        depth: 1

    - name: install npm packages
      npm: name={{ item }} state=latest global=yes
      with_items:
        - appium
        - create-react-native-app
        - eslint
        - grow
        - http-server
        - n
        - wd

    # Update pip and setuptools
    - shell: pip install --upgrade pip
      register: result
      changed_when: ‘”Requirement already up-to-date” not in result.stdout’

    - shell: pip install --upgrade setuptools
      register: result
      changed_when: ‘”Requirement already up-to-date” not in result.stdout'

    # Install (sphinx) python package.
    - pip:
      name: sphinx

    # Vim plugin manager
    - name: dein work directory
      file: path=/Users/{{ username }}/.vim/dein/ state=directory
    - name: download dein installer
      get_url:
        url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
        dest: /Users/{{ username }}/.vim/dein/installer.sh
    - name: install dein
      command: sh /Users/{{ username }}/.vim/dein/installer.sh /User/{{ username }}/.vim/dein

    # macOS settings
    - name: locate on
      become: yes
      command: launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
