---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    username: s.oikawa

  tasks:
    - name: tap repositories
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - homebrew/binary
        - caskroom/cask

    - name: install homebrew packages
      homebrew: name={{ item }} state=latest
      with_items:
        - hh
        - node
        - pwgen
        - tig
        - tree
        - wget

    - name: install homebrew cask packages
      homebrew_cask: name={{ item }} state=present
      with_items:
        - alfred
        - avira-antivirus
        - boostnote
        - coteditor
        - cyberduck
        - docker
        - dropbox
        - firefox
        - ganttproject
        - github-desktop
        - google-chrome
        - google-cloud-sdk
        - google-japanese-ime
        - hipchat
        - iterm2
        - java
        - kindle
        - macvim
        - slack
        - skitch
        - sourcetree
        # appstore LICENSE problem
        #- moom
        # not exists in cask
        #- feedly
        #- kobito
        #- tomato one
        #- wunderlist
        #- yorufukurou
        #

    # Bash-it
    - git:
        repo: https://github.com/Bash-it/bash-it.git
        dest: /Users/{{ username }}/.bash_it
        depth: 1

    - name: install npm packages
      npm: name={{ item }} state=latest global=yes
      with_items:
        - eslint

    # Vim plugin manager
    - name: dein work directory
      file: path=/Users/{{ username }}/.vim/dein/ state=directory

    - get_url:
        url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
        dest: /Users/{{ username }}/.vim/dein/installer.sh

    - command: sh /Users/{{ username }}/.vim/dein/installer.sh /User/{{ username }}/.vim/dein
