---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    username: "{{ ansible_ssh_user }}"

  tasks:
    - name: tap repositories
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - homebrew/cask
        - homebrew/cask-fonts

    - name: install homebrew packages
      homebrew: name={{ item }} state=latest update_homebrew=no upgrade_all=no
      with_items:
        - circleci
        - fabric
        - gibo
        - go
        - hh
        - ideviceinstaller
        - node
        - libpq
        - pwgen
        - redis
        - rename
        - the_silver_searcher
        - tig
        - tree
        - wget
        - yarn

    - name: install homebrew cask packages
      homebrew_cask: name={{ item }} state=present
      with_items:
        - alfred
        - altair-graphql-client
        - android-studio
        - avira-antivirus
        - coteditor
        - cyberduck
        - db-browser-for-sqlite
        - deepl
        - discord
        - docker
        - dropbox
        - dynalist
        - firefox
        - fork
        - google-chrome
        - google-drive-file-stream
        # permission problem..
        #- google-cloud-sdk
        - google-japanese-ime
        - iterm2
        - java
        - kindle
        - krisp
        - macvim
        - mongodb-compass
        - notion
        - obsidian
        - slack
        - skitch
        - sourcetree
        - visual-studio-code
        - zoomus
        - 1password
        # appstore LICENSE problem
        #- moom
        # not exists in cask
        #- feedly
        #- todoist
        #- google file stream

    - name: install Bash-it
      git:
        repo: https://github.com/Bash-it/bash-it.git
        dest: /Users/{{ username }}/.bash_it
        depth: 1

    - name: install npm packages
      npm: name={{ item }} state=latest global=yes
      with_items:
        - aws-amplify/cli
        - eslint
        - gatsby-cli
        - http-server
        - n
        - next
        - node-static
        - now
        - npm-check-updates
        - wd

    # Update pip and setuptools
    - shell: pip install --upgrade pip
      register: result
      changed_when: ‘”Requirement already up-to-date” not in result.stdout’

    - shell: pip install --upgrade setuptools
      register: result
      changed_when: ‘”Requirement already up-to-date” not in result.stdout'

    # Install (sphinx) python package.
    - pip:
      name: sphinx

    # Vim plugin manager
    - name: dein work directory
      file: path=/Users/{{ username }}/.vim/dein/ state=directory
    - name: download dein installer
      get_url:
        url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
        dest: /Users/{{ username }}/.vim/dein/installer.sh
    - name: install dein
      command: sh /Users/{{ username }}/.vim/dein/installer.sh /User/{{ username }}/.vim/dein

    # macOS settings
    - name: locate on
      become: yes
      command: launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

    - name: show hidden files
      become: yes
      command: defaults write com.apple.finder AppleShowAllFiles TRUE

    - name: does not create .DS_Store
      become: yes
      command: defaults write com.apple.desktopservices DSDontWriteNetworkStores True
