---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    username: "{{ ansible_ssh_user }}"

  tasks:
    - name: tap repositories
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - homebrew/cask
        - homebrew/cask-fonts
        - homebrew/cask-versions

    - name: install homebrew packages
      homebrew: name={{ item }} state=latest update_homebrew=no upgrade_all=no
      with_items:
        - direnv
        - docker
        - fabric
        - gh
        - gibo
        - go
        - hh
        - ideviceinstaller
        - node
        - nodenv
        - libpq
        - lsusb
        - rbenv
        - redis
        - rename
        - the_silver_searcher
        - tig
        - tree
        - watchman
        - wget
        - yarn

    - name: install homebrew cask packages
      homebrew_cask: name={{ item }} state=present
      with_items:
        - adobe-acrobat-reader
        - alfred
        - android-studio
        - appcleaner
        - asana
        - authy
        - charles
        - chatgpt
        - coteditor
        - cyberduck
        - discord
        - dropbox
        - firefox
        - flipper
        - fork
        - github
        - google-chrome
        - google-chrome-canary
        - google-drive-file-stream
        # permission problem..
        #- google-cloud-sdk
        - google-japanese-ime
        - iterm2
        - kindle
        - logseq
        - macvim
        - meetingbar
        - microsoft-edge
        - mongodb-compass
        - nektos/tap/act
        - netnewswire
        - ngrok
        - notion
        - postman
        - shottr
        - slack
        - skitch
        - react-native-debugger
        - visual-studio-code
        - zoomus
        - 1password
        # appstore LICENSE problem
        #- moom
        # not exists in cask
        #- feedly
        #- google file stream

    - name: install Bash-it
      git:
        repo: https://github.com/Bash-it/bash-it.git
        dest: /Users/{{ username }}/.bash_it
        depth: 1

    - name: install npm packages
      npm: name={{ item }} state=latest global=yes
      with_items:
        - aws-amplify/cli
        - eslint
        - gatsby-cli
        - http-server
        - n
        - next
        - node-static
        - now
        - npm-check-updates
        - wd

    # Update pip and setuptools
    - shell: pip install --upgrade pip
      register: result
      changed_when: ‘”Requirement already up-to-date” not in result.stdout’

    - shell: pip install --upgrade setuptools
      register: result
      changed_when: ‘”Requirement already up-to-date” not in result.stdout'

    # Install (sphinx) python package.
    - pip:
      name: sphinx

    # Vim plugin manager
    - name: dein work directory
      file: path=/Users/{{ username }}/.vim/dein/ state=directory
    - name: download dein installer
      get_url:
        url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
        dest: /Users/{{ username }}/.vim/dein/installer.sh
    - name: install dein
      command: sh /Users/{{ username }}/.vim/dein/installer.sh /User/{{ username }}/.vim/dein

    # macOS settings
    - name: locate on
      become: yes
      command: launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

    - name: show hidden files
      become: yes
      command: defaults write com.apple.finder AppleShowAllFiles true

    - name: does not create .DS_Store
      become: yes
      command: defaults write com.apple.desktopservices DSDontWriteNetworkStores true

    - name: turn off power chime
      become: yes
      command: defaults write com.apple.PowerChime ChimeOnNoHardware -bool true
